### ISSUE TITLE
org.apache.http.conn.HttpHostConnectException: Connect to localhost:80 failed: Connection refused

### ISSUE THREAD

**Issue by adriancobb** [fusepoolP3/p3-batchrefine#12]
Hi, 

I set up an apache server locally, and was trying to run BatchRefine as follows:

`curl -XPOST -H 'Content-Type:text/csv' --data-binary @universityData2.csv 'localhost:8310/?refinejson=http://localhost/university.json'`

But I only got an error message:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /. Reason:
<pre>    org.apache.http.conn.HttpHostConnectException: Connect to localhost:80 [localhost/127.0.0.1, localhost/127.0.0.1] failed: Connection refused</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

BatchRefine reported:

```
:25:07.037 [...BatchRefineTransformer] User-Agent:curl/7.35.0 (537323ms)
02:25:07.038 [...BatchRefineTransformer] Expect:100-continue (1ms)
02:25:07.038 [...BatchRefineTransformer] Content-Type:text/csv (0ms)
02:25:07.038 [...BatchRefineTransformer] Accept:*/* (0ms)
02:25:07.038 [...BatchRefineTransformer] Host:localhost:8310 (0ms)
02:25:07.039 [...BatchRefineTransformer] Content-Length:7735175 (1ms)
02:25:07.047 [...BatchRefineTransformer] ----------------------------------------------------- (8ms)
02:25:10.719 [...BatchRefineTransformer] GET http://localhost/university.json HTTP/1.1 (3672ms)
[qtp1816920494-15] WARN org.eclipse.jetty.servlet.ServletHandler - /
org.apache.http.conn.HttpHostConnectException: Connect to localhost:80 [localhost/127.0.0.1, localhost/127.0.0.1] failed: Connection refused
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at eu.spaziodati.batchrefine.transformer.BatchRefineTransformer.performRequest(BatchRefineTransformer.java:227)
	at eu.spaziodati.batchrefine.transformer.BatchRefineTransformer.fetchTransform(BatchRefineTransformer.java:106)
	at eu.spaziodati.batchrefine.transformer.SynchronousTransformer$1.writeData(SynchronousTransformer.java:64)
	at eu.fusepool.p3.transformer.server.handler.TransformerServlet.writeResponse(TransformerServlet.java:62)
	at eu.fusepool.p3.transformer.server.handler.SyncTransformerServlet.handlePost(SyncTransformerServlet.java:45)
	at eu.fusepool.p3.transformer.server.handler.AbstractTransformingServlet.service(AbstractTransformingServlet.java:46)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:208)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:271)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:517)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
	... 32 more

```

However, I can access `http://localhost/university.json` in web browser without a problem. 

How could I solve this problem?

Thanks!

**Comment by ktk** [comment]
@adriancobb you tried to get the config from localhost on port 80, it seems that you do not run a service there. I once wrote a more elaborate tutorial about batchrefine, drop me an email to adrian.gschwend at zazuko.com and I will send you a markdown of it (never made it public).
