### ISSUE TITLE
Weird behavior with some characters appearing string arguments 

### ISSUE THREAD

**Issue by ondrejhlavacek** [fusepoolP3/p3-batchrefine#9]
When character `Á` is present in an argument of an operation  batchrefine returns unchanged dataset.

Data example
```
"col1","col2"
"Á","Á"
"B","B"
"Č","Č"
```

Operations JSON example
```
[
    {
        "op": "core/column-addition",
        "description": "Create column col1_new at index 1 based on column col1 using expression grel:value",
        "engineConfig": {
            "mode": "row-based",
            "facets": []
        },
        "newColumnName": "col1_new",
        "columnInsertIndex": 1,
        "baseColumnName": "col1",
        "expression": "grel:value",
        "onError": "set-to-blank"
    },
    {
        "op": "core/column-addition",
        "description": "Create column col2_new at index 3 based on column col2 using expression grel:value",
        "engineConfig": {
            "mode": "row-based",
            "facets": []
        },
        "newColumnName": "col2_new",
        "columnInsertIndex": 3,
        "baseColumnName": "col2",
        "expression": "grel:value",
        "onError": "set-to-blank"
    },
    {
        "op": "core/mass-edit",
        "description": "Mass edit cells in column col1_new",
        "engineConfig": {
            "mode": "row-based",
            "facets": []
        },
        "columnName": "col1_new",
        "expression": "value",
        "edits": [
            {
                "fromBlank": false,
                "fromError": false,
                "from": [
                    "Á"
                ],
                "to": "A"
            }
        ]
    },
    {
        "op": "core/mass-edit",
        "description": "Mass edit cells in column col2_new",
        "engineConfig": {
            "mode": "row-based",
            "facets": []
        },
        "columnName": "col2_new",
        "expression": "value",
        "edits": [
            {
                "fromBlank": false,
                "fromError": false,
                "from": [
                    "Č"
                ],
                "to": "C"
            }
        ]
    }
]
```

Note, that removing the `"Á" -> "A"` replacement fixes it. `"Č" -> "C"` works fine though!

**Comment by andreybratus** [comment]
I will check this issue, thank you for reporting.

**Comment by andreybratus** [comment]
I managed to replicate the issue. Batchrefine sends the transformation rules to Openrefine correctly, but in OpenRefine log I observe the following stacktrace:

```
16:14:03.799 [                  command] Exception caught (5ms)
org.json.JSONException: Expected a ',' or ']' at 766 [character 767 line 1]
       	at org.json.JSONTokener.syntaxError(JSONTokener.java:423)
       	at org.json.JSONArray.<init>(JSONArray.java:143)
       	at org.json.JSONTokener.nextValue(JSONTokener.java:356)
       	at org.json.JSONObject.<init>(JSONObject.java:210)
       	at org.json.JSONTokener.nextValue(JSONTokener.java:352)
       	at org.json.JSONArray.<init>(JSONArray.java:125)
       	at org.json.JSONTokener.nextValue(JSONTokener.java:356)
       	at org.json.JSONObject.<init>(JSONObject.java:210)
       	at org.json.JSONTokener.nextValue(JSONTokener.java:352)
       	at org.json.JSONArray.<init>(JSONArray.java:125)
       	at org.json.JSONTokener.nextValue(JSONTokener.java:356)
       	at com.google.refine.util.ParsingUtilities.evaluateJsonStringToArray(ParsingUtilities.java:137)
```
however, the response is 200 OK, and it explains why the rules don't get applied at all. Whereas, if I apply the same rules from OpenRefine UI, it works fine.

**Comment by andreybratus** [comment]
Found the problem, the rules where not properly encoded, when sent to OR.

**Comment by ondrejhlavacek** [comment]
that was quick, thanks!

**Comment by andreybratus** [comment]
But I still have to make a release. Are you able to build it yourself and use the fix for now?

**Comment by ktk** [comment]
Thanks @andreybratus !
